[build]
  functions = "functions"
  publish = "dist" # Changed from "." to "dist"
[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200